name: Refresh GitHub Profile
run-name: Refresh GitHub Profile run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      output-dir:
        description: 'Path to the output directory'
        required: true
        default: 'tf/all-repositories/'
      debug:
        description: 'Enable debug output'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  refresh-profile:
    name: Refresh GitHub Profile
    runs-on: ubuntu-latest
    environment: "ci"

    concurrency:
      group: refresh-profile-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script (process_repositories.py)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        working-directory: ${{ github.workspace }}
        run: |
          python python-scripts/process_repositories.py \
            --org "${{ github.repository_owner }}" \
            --output-dir "${{ inputs.output-dir }}" \
            ${{ inputs.debug && '--debug' || '' }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: ${{ github.workspace }}/${{ inputs.output-dir }}

      - name: Terraform Validation and Formatting Checks
        id: validate
        uses: subhamay-bhattacharyya-gha/tf-validate-action@main
        with:
          terraform-dir: "tf"
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
        env:
          # IMPORTANT: give Terraform the org PAT
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN }}

      - name: Run TFLint
        uses: subhamay-bhattacharyya-gha/tf-lint-action@main
        with:
          tflint-ver: ${{ vars.TF_LINT_VER }}
          use-cache: "true"
          tflint-format: "compact"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN }}

      - name: Terraform Plan
        id: plan
        uses: subhamay-bhattacharyya-gha/tf-plan-action@main
        with:
          terraform-dir: "tf"
          tf-vars-file: "terraform.tfvars"
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN }}

      - name: Minimal create repo API test (creates then deletes)
        run: |
          set -e
          body='{"name":"pat-repo-test","private":true}'
          # create
          curl -s -X POST \
            -H "Authorization: Bearer $GH_ORG_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/subhamay-bhattacharyya/repos \
            -d "$body" | jq .
          # delete
          curl -s -X DELETE \
            -H "Authorization: Bearer $GH_ORG_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/subhamay-bhattacharyya/pat-repo-test
        env:
          GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}

      - name: Terraform Apply
        id: apply
        uses: subhamay-bhattacharyya-gha/tf-apply-action@main
        with:
          terraform-dir: "tf"
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          ci-pipeline: "false"
        env:
          # IMPORTANT: inputs != env. Use env for Terraform.
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
