name: Refresh GitHub Profile
run-name: Refresh GitHub Profile run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      output-dir:
        description: 'Path to the output directory'
        required: true
        default: 'terraform-code/all-repositories/'
      debug:
        description: 'Enable debug output'
        required: false
        default: false
        type: boolean

jobs:
  refresh-profile:
    name: Refresh GitHub Profile
    runs-on: ubuntu-latest

    # Prevent overlapping runs of THIS workflow on the same branch
    concurrency:
      group: refresh-profile-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script (process_repositories.py)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        working-directory: ${{ github.workspace }}
        run: |
            python python-scripts/process_repositories.py \
            --org "${{ github.repository_owner }}" \
            --output-dir "${{ inputs.output-dir }}" \
            ${{ inputs.debug && '--debug' || '' }}

      # - name: Print the output files
      #   working-directory: ${{ github.workspace }}/${{ inputs.output-dir }}
      #   shell: bash
      #   run: |
      #     echo "Output files:"
      #     ls -alR
      #     echo "======= cloudformation_repos.json ==================="
      #     cat cloudformation_repos.json|jq
      #     echo "======= terraform_repos.json ========================"
      #     cat terraform_repos.json|jq
      #     echo "======= currently_working_repos.json ================"
      #     cat currently_working_repos.json|jq

      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: ${{ github.workspace }}/${{ inputs.output-dir }}
